### ISSUE TITLE
Permissions don't copy correctly

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [cyclaero/clone#2]
Hi. I do love this program. cheers!

However, I hit on a problem where permissions sometimes weren't copied properly under certain conditions. Investigating, it turns out that if the source file system is  mounted readonly, u+w is always set on the copied file.

I'm using FreeBSD-stable and the latest version of clone from ports.

I tracked this down in the source to this:

util.h :

#define modperms(mode) (mode&ALLPERMS | ((gSourceRdOnly) ? S_IWUSR : 0))

Cheers, Jamie

**Comment by cyclaero** [comment]
Yes, I remember this. This was an ad-hoc work around when I wanted to copy files from a DVD and all the files were read only. I will mark this as a bug, and I will investigate the issue at the next weekend. I thought that the readonly files system mangles the permission, anyway, the solution is not a correct one.

For the time being please change the respective `#define` to:
`#define modperms(mode) (mode&ALLPERMS)`

Thank you for reporting the issue.

Best regards

Rolf

**Comment by Jamie-Landeg-Jones** [comment]
Thanks for the quick response!

In my case, the read-only filesystem was a UFS2 snapshot, I've often done a "cp -p" off these in the past with no apparent issues.. Having said that, those files were likely u+w already!

Not a major issue, but that for looking into this!

Cheers,
Jamie

**Comment by cyclaero** [comment]
Thank you for reporting the issue. I removed this workaround completely, I now see this was nonsense. You're right, the permissions are not mangled by mounting a file system readonly.

Closed with commit 9eaece6

**Comment by Jamie-Landeg-Jones** [comment]
Cheers!  I was going to submit a patch update to the FreeBSD port, but I note you are the maintainer there anyway!

2 options I'd like are the ability to preserve sparse files, and the option to process entries in lexicographical order, as with "find -s"...

Do you accept patches?  :-)

Cheers, Jamie

**Comment by cyclaero** [comment]
Yes, I am open for patches, however, please let us avoid adding third party dependencies. What do you mean with sparse files?

**Comment by Jamie-Landeg-Jones** [comment]
Hi. Cool. I'll add it to my todo list! And I agree about third party dependencies - they have their place, but not with something lean like clone.

As for sparse files, "clone" makes a complete copy of a file, without preserving its sparseness. BSD "cp" does similar. "rsync", BSD "tar", and GNU "cp" preserve sparseness.

GNU cp and BSD tar default to preserving sparseness, whilst GNU cp also has an option to maximise sparseness on copy.

Probably best if I show an example, from FreeBSD 12-stable:

The disk block allocation for the file (in K) is shown in the first column. The test file is a 2Mb file which only contains contains about 8K of real data.

Note how the allocated number of blocks for the file change with "cp" and "clone". Note that "tar" records sparseness information, and preserves it on extract.

Hope this is clearer, cheers, Jamie
```
02:55 (143) "~/pp" jamie@thompson% cat screendump

21:11 (63) "~/pp" jamie@thompson% l
total 12
4 drwx------   3 jamie  jamie  -   512  6 Aug 21:11 ./
4 drwxr-x---  63 jamie  jamie  - 2,560  6 Aug 21:06 ../
4 drwx------   2 jamie  jamie  -   512  6 Aug 21:07 original/

21:11 (64) "~/pp" jamie@thompson% l original/
total 104
 4 drwx------  2 jamie  jamie  -       512  6 Aug 21:07 ./
 4 drwx------  3 jamie  jamie  -       512  6 Aug 21:11 ../
96 -rw-r--r--  1 jamie  jamie  - 2,097,152  6 Aug 21:07 sparse-file

21:11 (65) "~/pp" jamie@thompson% cp -vr original/ cp
original/ -> cp
original/sparse-file -> cp/sparse-file

21:12 (66) "~/pp" jamie@thompson% gcp -vr original/ gcp
'original/' -> 'gcp'
'original/sparse-file' -> 'gcp/sparse-file'

21:12 (67) "~/pp" jamie@thompson% clone original/ clone
File tree cloning by Dr. Rolf Jansen (c) 2013-2017 - Version 1.0.7 (r80)
clone original/ clone/
+
2 items copied, 2.0 MB in 0.01 s -- 277.0 MB/s
Leaked memory: 0 bytes
No errors occured.

21:12 (68) "~/pp" jamie@thompson% tar cf original.tar original/

21:12 (69) "~/pp" jamie@thompson% tar cf cp.tar cp

21:12 (70) "~/pp" jamie@thompson% tar cf gcp.tar gcp

21:13 (71) "~/pp" jamie@thompson% tar cf clone.tar clone

21:13 (72) "~/pp" jamie@thompson% l *.tar
2112 -rw-------  1 jamie  jamie  - 2,099,200  6 Aug 21:13 clone.tar
2112 -rw-------  1 jamie  jamie  - 2,099,200  6 Aug 21:12 cp.tar
  68 -rw-------  1 jamie  jamie  -    69,120  6 Aug 21:13 gcp.tar
  68 -rw-------  1 jamie  jamie  -    69,120  6 Aug 21:12 original.tar

21:13 (73) "~/pp" jamie@thompson% l */*
2080 -rw-r--r--  1 jamie  jamie  - 2,097,152  6 Aug 21:07 clone/sparse-file
2080 -rw-------  1 jamie  jamie  - 2,097,152  6 Aug 21:12 cp/sparse-file
  96 -rw-------  1 jamie  jamie  - 2,097,152  6 Aug 21:12 gcp/sparse-file
  96 -rw-r--r--  1 jamie  jamie  - 2,097,152  6 Aug 21:07 original/sparse-file

21:28 (74) "~/pp" jamie@thompson% l
total 4384
   4 drwx------   6 jamie  jamie  -       512  6 Aug 21:28 ./
   4 drwxr-x---  63 jamie  jamie  -     2,560  6 Aug 21:22 ../
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:07 clone/
2112 -rw-------   1 jamie  jamie  - 2,099,200  6 Aug 21:13 clone.tar
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:12 cp/
2112 -rw-------   1 jamie  jamie  - 2,099,200  6 Aug 21:12 cp.tar
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:12 gcp/
  68 -rw-------   1 jamie  jamie  -    69,120  6 Aug 21:13 gcp.tar
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:07 original/
  68 -rw-------   1 jamie  jamie  -    69,120  6 Aug 21:12 original.tar

21:28 (75) "~/pp" jamie@thompson% rm -r clone cp gcp original
recursively remove 4 dirs? y

21:28 (76) "~/pp" jamie@thompson% l
total 4368
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:28 ./
   4 drwxr-x---  63 jamie  jamie  -     2,560  6 Aug 21:22 ../
2112 -rw-------   1 jamie  jamie  - 2,099,200  6 Aug 21:13 clone.tar
2112 -rw-------   1 jamie  jamie  - 2,099,200  6 Aug 21:12 cp.tar
  68 -rw-------   1 jamie  jamie  -    69,120  6 Aug 21:13 gcp.tar
  68 -rw-------   1 jamie  jamie  -    69,120  6 Aug 21:12 original.tar

21:28 (77) "~/pp" jamie@thompson% tar xf clone.tar

21:28 (78) "~/pp" jamie@thompson% tar xf cp.tar

21:28 (79) "~/pp" jamie@thompson% tar xf gcp.tar

21:28 (80) "~/pp" jamie@thompson% tar xf original.tar

21:28 (81) "~/pp" jamie@thompson% l
total 4384
   4 drwx------   6 jamie  jamie  -       512  6 Aug 21:28 ./
   4 drwxr-x---  63 jamie  jamie  -     2,560  6 Aug 21:22 ../
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:07 clone/
2112 -rw-------   1 jamie  jamie  - 2,099,200  6 Aug 21:13 clone.tar
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:12 cp/
2112 -rw-------   1 jamie  jamie  - 2,099,200  6 Aug 21:12 cp.tar
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:12 gcp/
  68 -rw-------   1 jamie  jamie  -    69,120  6 Aug 21:13 gcp.tar
   4 drwx------   2 jamie  jamie  -       512  6 Aug 21:07 original/
  68 -rw-------   1 jamie  jamie  -    69,120  6 Aug 21:12 original.tar

21:28 (82) "~/pp" jamie@thompson% l */*
2080 -rw-------  1 jamie  jamie  - 2,097,152  6 Aug 21:07 clone/sparse-file
2080 -rw-------  1 jamie  jamie  - 2,097,152  6 Aug 21:12 cp/sparse-file
  96 -rw-------  1 jamie  jamie  - 2,097,152  6 Aug 21:12 gcp/sparse-file
  96 -rw-------  1 jamie  jamie  - 2,097,152  6 Aug 21:07 original/sparse-file
```

**Comment by cyclaero** [comment]
I have to admit, that I never paid attention to the number of allocated blocks for a file. For me a file had a file size, which I can lookup in it's `struct stat`, and yes clone does exactly this, and copies the number of bytes as reported by stat.

Now I see, that `stat struct` got the fields `st_blocks` and `st_blksize`.

In order to preseve sparsenes of a file, would it then be sufficient to check `if (st_blocks*st_blksize < st_size)`, and in case yes copy over only the respective blocks and adjust the file size somehow? In case no, do a copy as usual.

I understand the concept, and clone is supposed to produce clones as exact as possible, so yes, it needs to preserve sparseness.

**Comment by Jamie-Landeg-Jones** [comment]
Sparse files are where blocks of contiguous empty space (x00 character) are not physically allocated to a sector, but instead just flagged in the metadata. (aka "holes")

When holes are read, the data is presented to the reader as a chunk of zeros (x00)

Holes are created by seeking forward past EOF on a write, so, instead of writing (say 4096) Kbytes, you'd seek. On the command line you can do:

dd if=/dev/null bs=1k seek=4096 of=test

which, as it has no data at all, has a zero physical size:

0 -rw-------   1 jamie  operator  -    4,194,304  7 Aug 05:04 test

Freebsd (and others) also have the command "truncate" which despite its name, will truncate OR expand a file, so the above example could be achieved by:

truncate -s4m test

truncate(2) exists, but it's use to extend a file isn't portable.

Those examples may be useful for testing, playing around, but I presume they are irelevant for clone, as it won't be doing preallocating, just writing as it goes.

This is where my knowledge gets hazy... There is no way to tell which blocks are 'holes' and which blocks are literal zeros, without hacky delving into the internals, which would require root, and be different for each filesystem.

From what I gather, to create fully sparsed files, when you read in the data, if you get a zero, don't write a zero, but keep a count of them until you hit a non-zero. At that stage, instead of writing the zeros, seek over them. The OS will then do the right thing - ie. it will write zeros for the remaining bits of the current block, but mark any fully zero blocks as holes.

Things I am unsure of : 

Can we seek a byte at a time and the OS will do the right thing, without us having to track it? Would that be too inefficient anyway?

Simiarly, if we seek 10 blocks in one go, is it more efficient than seeking 1 block 10 times in a row?

Also, if the blocksize <---> filesize check shows the file contains no sparse holes, presumably more efficient to not use the sparse-aware code at all?

As for how GNU cp manages to keep the same amount of blocks (remember, in the example above my 96 block 2meg file, if i opened it and wrote 400K's worth of zeros somewhere in the middle, the block size would increase 400K but the file on reading would be identical)... I don't know. It can't tell which bits are holes and which bits are blocks full of zeros. My **guess** is that it just goes through a file skipping over block of zero, as I mentioned above, but by checking (st_blocks*st_blocksize ) once it's created enough holes to match the allocated block / filesize discrepancy, it simply then reverts to writing zeros for the rest of the copy.... because if one section of a file is sparse, and another section is all zeros, it won't be able to tell which is which.

Most utilities that support sparse files have 3 options:

- No sparseness
- Preserve sparseness
- Full sparseness

Sorry this is a bit long winded, and not too clear. It ended up a bit of an incoherent brainstorm! But it's late! (gone 5am!)

This page is useful. It seems sparse files are supported on windows and mac os too.   https://en.wikipedia.org/wiki/Sparse_file

**Comment by Jamie-Landeg-Jones** [comment]
I've just found out that 'lseek' has been updated (on linux and freebsd at least) with SEEK_HOLE and SEEK_DATA

although the man page does say that filesystems may use those calls to return "bunches of zeros" and not necessarily actual holes(!) - still it may make the whole process more efficient

https://www.freebsd.org/cgi/man.cgi?query=lseek&sektion=2

and: https://lwn.net/Articles/440255/

**Comment by cyclaero** [comment]
The possibility of sparse holes in the middle of files makes everything more complicated than I thought by an order of magnitude. In case you're still willing to work on it, I like to suggest that you make a copy of the function `atomCopy()`, lines 618 - 703 in clone.c, as the basis, perhaps name it `sparseCopy()`, and step by step implement the checks for the holes and copy the chunks respectively. Given a positive sparseness check, this copy function would be used instead of the others.

Perhaps you saw this already. `atomCopy()` is a fallback copy routine, used in cases where the producer/consumer threaded copy would not be appropriate. I see the hypothetical `sparseCopy()` - please feel free to give it another name - similarly, maybe a drop-in replacement.

I am very busy otherwise in the moment, however, once you get something working, we can finalise it together, e.g. add a few flags, adapt the usage() and clone.1, etc.

For the time being, the sparseness check would also include whether we support this for the target file system.

**Comment by Jamie-Landeg-Jones** [comment]
Huge apologies for not replying to this - I'd originally decided to actually do some investigatory work into a solution before responding, but other things came along, and they don't seem to stop.

I will still keep an eye on this topic in the future, but I'm afraid it's now on the end of a very long todo list.

One thing to note: The FreeBSD port is marked to expire as unfetchable, because the source download URL is no longer valid..

Cheers, Jamie

**Comment by cyclaero** [comment]
Jamie, thank you very much for your kind note. No need to ask for apologies. Everything’s good.

This unfetchable mark was set, because my web-server was temporarily out of order. I wrote a kind message to the guy who set the mark, once the URL was valid again, but he didn’t respond and didn't take any action either. I am quite busy as well with another project, however, I will find some time to submit a minor update which would include a new working URL. I expect this to resolve the issue.

**Comment by Jamie-Landeg-Jones** [comment]
Hiya, thanks for the reply, and update. I was just unsure if you noticed - one of my bugbears with the ports system is that they mark things as deprecated but you don't necessarily notice until you try and reinstall! I've resurrected many ports on the past that were marked deprecated for trivial reasons, and then eventually deleted, but I hadn't noticed in time!

Still, we've all got more important things to deal with at the moment, so I hope all is ok there. No problems here, fortunately!

Cheers, Jamie
