### ISSUE TITLE
Possibly adding use-cases to README

### ISSUE THREAD

**Issue by lispstudent** [cyclaero/clone#3]
Hello,

I would like to start using `clone`, and I was wondering what kind of use-case would make its use preferable to `rsync`?

Thank you for `clone` and other useful tools for FreeBSD, like `ContentCGI`!

**Comment by cyclaero** [comment]
Sorry for the delay. I was quite busy in the last days. In addition I needed to think a bit about, _„what kind of use-case would make the use of clone preferable to rsync?“_ Off hand, I can tell you a few reasons:

1. rsync is NIH
2. on FreeBSD rsync does copy only the user’s extended attributes, not the system ones
3. rsync is a little bit slower than clone
4. clone does the most common backup tasks with no or a single command line option, while with rsync I always need to lookup the option-set which I would need, normally it is `-axAHX --fileflags`
5. one unique selling point of clone is, that it can very fast create a whole directory tree of any depth of hard links. This is extremely useful if we literally need to learn about changed or deleted file system items - for example, I [employed](https://github.com/cyclaero/zettair/blob/13a2ebdeca3da0ac037568f0bca022aea357db68/devel/src/Spider/spider#L49) this in the [Spider script](https://github.com/cyclaero/zettair/blob/master/devel/src/Spider/spider) which in combination with the [Zettair](https://github.com/cyclaero/zettair/tree/master/devel) search engine is a crucial part of the [search facility](https://github.com/cyclaero/ContentCGI/tree/master/plugins/search-delegate) of [ContentCGI](https://github.com/cyclaero/ContentCGI).

Reason 1 to 4 are mostly a matter of taste. Reason 5 is IMHO quite too special, for adding this to the general overview in the README.

I wrote a BLog post in German language, on how clone fits into my [backup strategy](https://obsigna.com/articles/1539003644.html).

There is another BLog post in english which focusses on the technical details of [cloning an UFS volume to another disk](https://obsigna.com/articles/1643414951.html).

However, both could be achieved by rsync as well.

**Comment by lispstudent** [comment]
Thank you for the detailed answer. I started using `clone`, I like it very much. I prefer using `clone` rather than `rsync` especially when dealing with hard links. Its syntax more easily maps to my workflow. Somehow, I feel safer in having my intention executed as intended.

Thank you for linking to those instructive articles. I am inspired by clone's design and implementation.
